#演示profiles，这里采用分段式，还可以用application-dev的方式和application.properties
#还可以给idea设置spring.profiles.active，还可以执行jar的时候使用命令行--spring.profiles.active=pro的方式设置
---
spring:
  profiles:
    active: dev #激活profile

#  mvc:
#    static-path-pattern: /res/** # 加前缀访问，这个会导致welcome失效

#  resources:
#    static-locations: [classpath:/haha/] # 自定义静态资源目录

---
server:
  port: 8084

spring:
  profiles: dev

---
server:
  port: 8085

spring:
  profiles: pro