server:
  port: 8085

# 配置mybatis
mybatis:
  type-aliases-package: com.example.springbootproject.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml


spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/market?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    maxActive: 20
    maxWait: 60000
    validationQuery: SELECT 1 FROM study

    # druid监控
    filters: stat, wall, log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectProperties: druid.stat.mergeMysql=true;druid.stat.SlowSqlMillis=500



