server:
  port: 8085

# 配置mybatis
mybatis:
  type-aliases-package: com.example.springbootproject.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml


spring:
  # mysql
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/market?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    maxActive: 20
    maxWait: 60000
    validationQuery: SELECT 1 FROM study

    # druid监控
    filters: stat, wall, log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectProperties: druid.stat.mergeMysql=true;druid.stat.SlowSqlMillis=500

  # redis
  redis:
    host: 47.92.158.139
    port: 6973
    database: 8
    password: password01
    timeout: 3000
    # jedis 连接池
    jedis:
      pool:
        max-active: 50
        max-wait: 300
        max-idle: 20
        min-idle: 2
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false