#演示profiles，这里采用分段式，还可以用application-dev的方式和application.properties
#还可以给idea设置spring.profiles.active，还可以执行jar的时候使用命令行--spring.profiles.active=pro的方式设置

#由spring boot 解析
#server:
#  port: 8082

#自定义解析的数据
uname: 马六

person:
  name: 王武
  flower-name: ${person.name:uname},
  alias: ${uname}
  age: ${random.int}
  hobby:
    - 唱歌
    - 美食

#纯量
msg1: 'hello \n world'
msg2: "hello \n world"


---
spring:
  profiles:
    active: dev #激活profile

  #  mvc:
  #    static-path-pattern: /res/** # 加前缀访问，这个会导致welcome失效

  #  resources:
  #    static-locations: [classpath:/haha/] # 自定义静态资源目录

  mvc:
    contentnegotiation:
      # 开启基于url的format=xml或json的内容协商
      favor-parameter: true

---
server:
  port: 8084

spring:
  profiles: dev

---
server:
  port: 8085

spring:
  profiles: pro