#由spring boot 解析
#server:
#  port: 8082

#自定义解析
uname: 马六

person:
  name: 王武,
  flower-name: ${person.name:uname},
  alias: ${uname}
  age: ${random.int}
  hobby:
    - 唱歌
    - 美食

#纯量
msg1: 'hello \n world'
msg2: "hello \n world"
